version: "3.9"
services:
  frontend:
    build: ./Pensive.Front
    ports:
      - "3000:3000"
  backend:
    build: ./Pensive.Back
    ports:
      - "5001:80"
    depends_on:
      - database
  database:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: pensive
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin12345
